### ISSUE TITLE
Chunking the blob is broken for specific size of payload

### ISSUE THREAD

**Issue by eriknelson** [fusor/ansibleapp#16]
Produces broken dockerfile for this ansibleapp file:

```
id: 071f3645-7189-4808-b9c2-2d29c143e80d
name: ansibleapp/external-mlab-ansibleapp
description: Bindable ansibleapp shim for external mlab mongodb database
bindable: true
async: "unsupported"
parameters:
  - name: binding_key
    description: key used to identify the binding info
    type: string
  - name: ip
    description: mongodb ip address
  - name: port
    description: mongodb port
  - name: db
    description: mongodb database
  - name: acct_one_user
    description: first account user
  - name: acct_one_pass
    description: second account pass
  - name: acct_two_user
    description: second account user
  - name: acct_two_pass
    description: second account pass
```

Blob was not correctly closed by quote, had to go in and add:

```
# cat Dockerfile
FROM ansibleapp/ansibleapp-base
# MAINTAINER {{ $MAINTAINER }}

LABEL "com.redhat.ansibleapp.version"="0.1.0"
LABEL "com.redhat.ansibleapp.spec"=\
"aWQ6IDA3MWYzNjQ1LTcxODktNDgwOC1iOWMyLTJkMjljMTQzZTgwZApuYW1lOiBhbnNpYmxlYXBw\
L2V4dGVybmFsLW1sYWItYW5zaWJsZWFwcApkZXNjcmlwdGlvbjogQmluZGFibGUgYW5zaWJsZWFw\
cCBzaGltIGZvciBleHRlcm5hbCBtbGFiIG1vbmdvZGIgZGF0YWJhc2UKYmluZGFibGU6IHRydWUK\
YXN5bmM6ICJ1bnN1cHBvcnRlZCIKcGFyYW1ldGVyczoKICAtIG5hbWU6IGJpbmRpbmdfa2V5CiAg\
ICBkZXNjcmlwdGlvbjoga2V5IHVzZWQgdG8gaWRlbnRpZnkgdGhlIGJpbmRpbmcgaW5mbwogICAg\
dHlwZTogc3RyaW5nCiAgLSBuYW1lOiBpcAogICAgZGVzY3JpcHRpb246IG1vbmdvZGIgaXAgYWRk\
cmVzcwogIC0gbmFtZTogcG9ydAogICAgZGVzY3JpcHRpb246IG1vbmdvZGIgcG9ydAogIC0gbmFt\
ZTogZGIKICAgIGRlc2NyaXB0aW9uOiBtb25nb2RiIGRhdGFiYXNlCiAgLSBuYW1lOiBhY2N0X29u\
ZV91c2VyCiAgICBkZXNjcmlwdGlvbjogZmlyc3QgYWNjb3VudCB1c2VyCiAgLSBuYW1lOiBhY2N0\
X29uZV9wYXNzCiAgICBkZXNjcmlwdGlvbjogc2Vjb25kIGFjY291bnQgcGFzcwogIC0gbmFtZTog\
YWNjdF90d29fdXNlcgogICAgZGVzY3JpcHRpb246IHNlY29uZCBhY2NvdW50IHVzZXIKICAtIG5h\
bWU6IGFjY3RfdHdvX3Bhc3MKICAgIGRlc2NyaXB0aW9uOiBzZWNvbmQgYWNjb3VudCBwYXNzCg==\

ADD ansibleapp /opt/ansibleapp

RUN useradd -u 1001 -r -g 0 -M -b /opt/ansibleapp -s /sbin/nologin -c "ansibleapp user" ansibleapp
RUN chown -R 1001:0 /opt/ansibleapp
USER 1001
```

Will cause a "playbook not found" error, as the ADD does not run correctly.
